id: P010483
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:52:09.214005
source_metadata:
  id: bdr:W1KG18291
  title: དམ་པའི་ཆོས་ཀྱི་ཐོབ་ཡིག་བསྟན་པའི་ནོར་རྫས།
  author: ''
  volumes:
    e9db71f932e34fdc9993150776e4814e:
      image_group_id: I1KG18296
      title: ''
      volume_number: 1
      total_pages: 542
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
